### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by kage622328** [kage622328/did_it#35]
## 概要
[GitHub Project "Did it開発プロジェクト"URL](https://github.com/users/kage622328/projects/1)

### 実装予定の機能
- [ ] ユーザー登録機能
- [ ] ユーザーパスワードリセット機能
- [ ] ユーザーメールアドレス変更機能
- [ ] ユーザー登録解除機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] お子さま登録機能
- [ ] お子さま登録削除機能
- [ ] お子さま編集機能
- [ ] やることリスト作成機能
- [ ] やることリスト編集機能
- [ ] やることリスト削除機能
- [ ] コイン追加機能
- [ ] いままでのがんばり確認機能

### 必要なページ
- [ ] トップページ
- [ ] 新規登録ページ
- [ ] ログインページ
- [ ] マイページ
- [ ] 保護者メニュー
- [ ] パスワードリセット申請ページ
- [ ] パスワードリセットページ
- [ ] メールアドレス変更リセットページ
- [ ] メールアドレス変更ページ
- [ ] お子さま登録状況ページ
- [ ] お子さま編集ページ
- [ ] お問い合わせページ
- [ ] お子さま用マイページ
- [ ] いままでのがんばりページ
- [ ] やることリスト作成ページ
- [ ] リスト詳細ページ
- [ ] やることリスト編集・削除ページ

## 気になっていること
Issueを作成中に一部、画面遷移図・ER図に変更が発生しました
具体的には
- お子さま登録機能をマイページ上で実装できるようにしたため、お子さま登録画面がなくなる
- お子さま編集画面がなかったので追加
- Coinテーブルはコインの総数が管理できれば良いのでListテーブルとのアソシエーションは作成しない
- Coinテーブルのcoin_typeカラムをamountに変更
です。

もしもう一度画面遷移図、ER図共にプルリクエストの提出が必要でしたらその旨ご教授いただけますと幸いです。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVP後で良いと感じたカードになります。

- パスワードリセット
- メールアドレス変更
- ボタンに動き
- お問い合わせ

**Comment by kage622328** [comment]
ご確認ありがとうございます。

ご指摘いただいたカード以外のものから優先的に開発を始め、MVPリリースに向けて実装を行っていこうと思います。
