### ISSUE TITLE
"MVPリリース"レビュー依頼

### ISSUE THREAD

**Issue by kage622328** [kage622328/did_it#87]
## 各種情報
サービス名: Did it
サービスURL: https://did-it.onrender.com
GitHubリポジトリ: https://github.com/kage622328/did_it

### READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

- [x] ユーザー登録機能
- [x] ユーザー登録解除機能
- [x] ログイン機能
- [x] ログアウト機能
- [x] お子さま登録機能
- [x] お子さま登録削除機能
- [x] お子さま編集機能
- [x] やることリスト作成機能
- [x] やることリスト編集機能
- [x] やることリスト削除機能
- [x] コイン追加機能
- [x] いままでのがんばり確認機能
 
以下"Issueベースの開発"レビュー時にMVP後の実装で可とのコメントをいただき、MVPリリース時には実装しておりません
- [ ] ユーザーパスワードリセット機能
- [ ] ユーザーメールアドレス変更機能

README作成時、タスクの登録は選択制で登録としておりましたが、現在手入力の形になっています
音符マークをクリックして流れる音楽はWeb Audio API、各ボタンクリック時の音は<audio>タグを使用して実装しております

## サービスイメージがわかるようなスクリーンショット
 - トップページ
 [![Image from Gyazo](https://i.gyazo.com/0847189f60a2d36dd0e5a8bc89d75aa4.png)](https://gyazo.com/0847189f60a2d36dd0e5a8bc89d75aa4)
- 保護者用マイページ
こどもの名前をクリックするとお子さま用マイページへ遷移
[![Image from Gyazo](https://i.gyazo.com/95ce33049af57cf3b2cccf49b9068f6b.png)](https://gyazo.com/95ce33049af57cf3b2cccf49b9068f6b)
- 保護者メニュー
[![Image from Gyazo](https://i.gyazo.com/aa249dcd17740b4338036f39ee18ab39.png)](https://gyazo.com/aa249dcd17740b4338036f39ee18ab39)
- お子さま登録状況一覧
編集画面への遷移、登録削除が行える
[![Image from Gyazo](https://i.gyazo.com/320a814fede2019cdc3df613d3fe2c3b.png)](https://gyazo.com/320a814fede2019cdc3df613d3fe2c3b)
- お子さま用マイページ
左上の音符ボタンをクリックすると音楽が流れる
各リストのボタン(青)をクリックすると音が鳴りリスト詳細ページへ遷移
リストが完了してコインを獲得すると、各リストの右側にコインマークが表示される
[![Image from Gyazo](https://i.gyazo.com/07e828689e82b1681f98a50dc5a7ea9b.png)](https://gyazo.com/07e828689e82b1681f98a50dc5a7ea9b)
- いままでのがんばりページ
完了したtask.bodyとその回数が一覧で確認できる
[![Image from Gyazo](https://i.gyazo.com/9da80a4ccd7138a37334843f6ce6c35f.png)](https://gyazo.com/9da80a4ccd7138a37334843f6ce6c35f)
- リスト詳細ページ
左上の音符マークをクリックすると音楽が流れる
各タスクボタンをクリックすると音がなり、taskのstatusがcompletedとなり「できた」マークが表示される
すべてのタスクが完了されると「コインをゲット！！」ボタンが表示される
「コインをゲット！！」ボタンをクリックすると音が鳴り、
お子さま用マイページのコインの数が1枚増える
コイン獲得後の「コインをゲット！！」ボタンは「コイン獲得済みだよ」と表示されてクリックできない
リスト編集ボタンをクリックするとリスト編集ページへ遷移する
[![Image from Gyazo](https://i.gyazo.com/118df83e1f34cc1daae5fe6e21b32e6a.png)](https://gyazo.com/118df83e1f34cc1daae5fe6e21b32e6a)
[![Image from Gyazo](https://i.gyazo.com/dbbcc4802bef9711ce6581a24c4168af.png)](https://gyazo.com/dbbcc4802bef9711ce6581a24c4168af)
- リスト編集ページ
[![Image from Gyazo](https://i.gyazo.com/d032cf6fa84143a9d85f7ead43e8ea9f.png)](https://gyazo.com/d032cf6fa84143a9d85f7ead43e8ea9f)

ご確認のほどよろしくお願いいたします。

**Comment by kenchasonakai** [comment]
LGTMです！

**Comment by kage622328** [comment]
ありがとうございます！卒業後も精進できるよう頑張ります！！
